#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
- hosts: all
  become: true
  roles:
    - role: ambari_common
  tags:
    - ambari-prereqs
    - hdp-install

- hosts: postgres
  become: true
  roles:
    - role: postgresql

- hosts: activemq
  become: true
  roles:
    - role:  activemq
- hosts: ambari-server
  become: true
  roles:
    - role: ambari_master
  tags:
    - ambari-server
    - hdp-install


- hosts: ambari-agent
  become: true
  roles:
    - role: ambari_slave
  tags:
    - ambari-agent
    - hdp-install

- hosts: ambari-server
  become: true
  roles:
    - role: ambari_config
  tags:
    - hdp-deploy

- hosts: hdp_test
  become: true
  roles:
    - role:  hdp_test
