#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
- name: install python-pip dependencies
  yum:
     name: "{{ item }}"
     state: latest
  with_items:
     - python-pip
     - python-devel
     - postgresql-devel
     - gcc
     
- name: create ~/.pip directory  
  file: path=~/.pip state=directory

- name: copying the template for python-pip.conf to node
  template:
    src=python.pip.j2
    dest=~/.pip/pip.conf
    backup=yes

- name: copying the template for python easy_install to node
  template:
    src=python.pydistutils.j2
    dest=~/.pydistutils.cfg
    backup=yes

- name: copying the template for python pypi to node
  template:
    src=python.pypirc.j2
    dest=~/.pypirc
    backup=yes
