#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
- name: copy ambari repo template
  template:
    src: "ambari.repo"
    dest: "/etc/yum.repos.d/ambari.repo"

- name: install ambari agent
  yum:
    name: ambari-agent
    state: installed
  register: result

- name: get the version of ambari agent
  shell: yum list installed ambari-agent | grep ambari-agent | awk '{print $2}' | cut -d'-' -f1 | cut -d':' -f2
  register: version
  changed_when: False
  args:
    warn: no

- name: locating ambari agent
  shell: whereis ambari-agent | tr " " %
  register: path
  
- name: generate ambari agent report
  shell: "{{ playbook_dir }}/report.sh ambari-agent {{ version.stdout }} N/A {{ path.stdout }} {{ ansible_fqdn }} success"
  delegate_to: localhost
  when: result|succeeded

- name: create ambari agent hostname script
  template:
    src: "{{ role_path }}/files/hostname.sh"
    dest: "/var/lib/ambari-agent/hostname.sh"
    mode: 0744
    owner: "{{ ambari_installation_user }}"
    group: "{{ ambari_installation_user }}"

- name: configure ambari server hostname in ambari agent configuration
  lineinfile:
    dest: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter }}"
    backup: yes
  with_items:
    - { regexp: "^.*hostname=.*$", line: "hostname={{ ambari_hosts[0]['name'] }}", insertafter: '\[server\]' }
    - { regexp: "^hostname_script=.*$", line: "hostname_script=/var/lib/ambari-agent/hostname.sh", insertafter: '\[agent\]'}

- name: start ambari agent
  service:
    name: ambari-agent
    state: restarted
    enabled: yes
  async: 20
  poll: 0

- name : check if ambari agent is up 
  wait_for : host={{ ansible_fqdn }} port=8670 delay=20

- name : wait for agent to register
  command : sleep 10
