foreman:
    architecture:
        - name: x86_64

    medium:
        - name: CentOShery
          path: http://10.129.6.237/repos/CentOS_7_x86_64/
          os-family: Redhat

    setting:
        - name: token_duration
          value: 360

    os:
        - name: centos7hery
          major: 7
          minor: 6
          description: centos7hery
          family: Redhat
          release-name: cemtos7
          password-hash: SHA512
          architecture:
            - name: x86_64
          provisioning-template:
            - name: Kickstart default
            - name: Kickstart default finish
            - name: Kickstart default PXELinux
            - name: Kickstart default iPXE
            - name: Kickstart default user data
          medium:
            - name: CentOShery
          partition-table:
            - name: Kickstart default
          parameters:
            version: "7"
            codename: "centos7hery"

    hostgroup_default:
          - name: host1
            parent:
            os: centos7hery
            architecture: x86_64
            medium: CentOShery
            partition-table: Kickstart default

    device_identifier:
          - name: enp0s3
