#!/usr/bin/python
# -*- coding: utf8 -*-
#Copyright:@BaeSystemsAI
#Original author: Heri Sutrisno
#Email:harry.sutrisno@baesystems.com
#Description:payload yml file for user


foreman:
    auth:
        fqdn: foreman.example.com
        ip: 10.11.12.5
        user: admin
        pass: as123

    #name = Required
    #fullname/description=optional
    domain:
        - name: example.com
          fullname: this is example.com

    subnet:
        - name: subnet1
          network: 10.11.12.0
          mask: 255.255.255.0
          gateway: 10.11.12.1
          dns-primary: 10.11.12.7
          dns-secondary: 8.8.8.8
          vlanid:
          domain:
            - name: example.com

    hostgroup:
        - name: master
          subnet: subnet1
          domain: example.com
          root-pass: as12345678

    hosts:
        - name: agent1
          hostgroup: master
          ip: 10.11.12.05
          mac: 080027CB0637
