#
## Software Copyright BAE Systems plc 2017. All Rights Reserved.
## BAE SYSTEMS, DETICA are trademarks of BAE Systems
## plc and may be registered in certain jurisdictions.
##
#---
## Create Config Files

- name: Create temp inventories directory
  file:
    path: {{ role_path }}/inventories
    state: directory

- name: Clean temp inventories directory
  file:
    state: absent
    path:  {{ role_path }}/inventories/


- name: Validate & Create config files
  shell: 'cd {{ role_path }}  && python scripts/config.py {{playbook_dir}}/config.yml {{ role_path }}'
  register: config
  run_once: true

- debug: msg="{{ config.stderr.split('\n')}}"
- debug: msg="{{ config.stdout.split('\n')}}"

- name: Create Ansible Inventory directories
  file:
    path: {{ playbook_dir }}/inventories
    state: directory

- name: Clean Ansible Inventory directories
  file:
    state: absent
    path:  {{ playbook_dir }}/inventories/


- synchronize:
    src: {{ role_path }}/inventories
    dest: {{ playbook_dir }}/inventories
  delegate_to: localhost



