#
## Software Copyright BAE Systems plc 2017. All Rights Reserved.
## BAE SYSTEMS, DETICA are trademarks of BAE Systems
## plc and may be registered in certain jurisdictions.
##
#---
## Create Config Files

- name: Create temp inventories directory
  file:
    path: "{{ role_path }}/inventories"
    state: directory

- name: Create temp inventories directory
  file:
    path: "{{ role_path }}/roles_config"
    state: directory


- name: Clean temp inventories directory
  file:
    state: absent
    path:  "{{ role_path }}/inventories/"


- name: Clean temp config directory
  file:
    state: absent
    path:  "{{ role_path }}/roles_config/"


- name: Validate & Create config files
  shell: 'cd {{ role_path }}/scripts  && python config.py {{playbook_dir}}/config.yml {{ role_path }}'
  register: config
  run_once: true

- debug: msg="{{ config.stderr.split('\n')}}"
- debug: msg="{{ config.stdout.split('\n')}}"

- name: Create Ansible Inventory directories
  file:
    path: "{{ playbook_dir }}/{{ inventoriesdir}}"
    state: directory

- name: Create Ansible Config files directories
  file:
    path: "{{ playbook_dir }}/roles_config"
    state: directory


- name: Clean Ansible Inventory directories
  file:
    state: absent
    path: "{{ playbook_dir }}/{{ inventoriesdir}}/"

- name: Clean Ansible Config files directories
  file:
    state: absent
    path: "{{ playbook_dir }}/roles_config/"

- name: Install rsync
  yum:
    name: rsync
    state: installed


- name: Synchronize inventories
  synchronize:
    src: "{{ role_path }}/inventories/"
    dest: "{{ playbook_dir }}/{{ inventoriesdir}}/"
  delegate_to: localhost

- name: Clean Ansible temp inventories
  file:
    state: absent
    path: "{{ role_path }}/inventories/"


- name: Synchronize config files directories
  synchronize:
    src: "{{ role_path }}/roles_config/"
    dest: "{{ playbook_dir }}/roles_config/"
  delegate_to: localhost

- name: Clean temp role config directories
  file:
    state: absent
    path: "{{ role_path }}/roles_config/"



- name: Copy Inventory list file
  copy:
   src: "{{ role_path}}/inventory_list"
   dest: "{{ playbook_dir}}/inventory_list"
   force: yes

- name: remove Inventory_list file
  file:
    state: absent
    path: "{{ role_path }}/inventory_list"

