---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package: name={{ docker_package }} state={{ docker_package_state }}

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes
