---

- name: Add Kibana repository.
  template:
    src: kibana.repo.j2
    dest: /etc/yum.repos.d/kibana.repo
    mode: 0644

- name: Install Kibana.
  package: name=kibana state=present

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "/etc/kibana/kibana.yml"
    owner: root
    group: root
    mode: 0644

- name: restart kibana
  service: name=kibana state=restarted

- name : check if kibana is up
  wait_for : host={{ kibana_hosts[0]['name'] }} port={{ kibana_port }} delay=5 timeout=180

