#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
- blockinfile: |
    dest=~/.bashrc backup=yes
    content="unset http_proxy
        unset https_proxy
        unset HTTP_PROXY
        unset HTTPS_PROXY"

- lineinfile:
    path: /etc/yum.conf
    regexp: '^proxy='
    line: ''

- name: backup /etc/environment
  shell: cp -f  /etc/environment /etc/env_backup

- name: cleanup /etc/environment
  shell: echo "" > /etc/environment

- name: copy centOS repo template
  template:
    src: "CentOS-Base.repo"
    dest: "/etc/yum.repos.d/CentOS-Base.repo"
    force: yes
 

