#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
- name: install open jdk
  any_errors_fatal: true
  yum: name=java-1.8.0-openjdk state=installed
  when: default_java_vendor == "openjdk" or default_java_vendor is undefined

- name: install oracle jdk
  any_errors_fatal: true
  yum: name={{ jdk_rpm }} state=present
  when: default_java_vendor == "oracle"
  
