#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
# defaults file for activemq-ansible-role
activemq_user: activemq
activemq_group:  activemq
activemq_install_dir: /opt
activemq_run_dir: "/opt/{{ activemq_user }}"
activemq_home_dir:  /var/lib/activemq
activemq_log_dir: /var/log/activemq

# default installation mode
activemq_skip_checksum: true
activemq_url_prefix: "{{ activemq_repo_url }}"

# calculate version
activemq_version_major: "5"
activemq_version_minor: "15"
activemq_version_patch: "0"

activemq_version: "{{ activemq_version_major }}.{{ activemq_version_minor }}.{{ activemq_version_patch }}"
activemq_url: "{{ activemq_url_prefix }}/apache-activemq-{{ activemq_version }}-bin.tar.gz"

activemq_env_vars:
  ACTIVEMQ_USER: "{{ activemq_user }}"
  ACTIVEMQ_BASE: "{{ activemq_run_dir }}"
