# User interface related settings
:ui:
   # Enable interactive queries?
     :interactive: true
   # Number of records listed per page
   # :per_page: 20
   # Location of shell history file
     :history_file: '~/.hammer/history'
   # Mark translated strings with X characters (for developers)
   #:mark_translated: false


# Enable/disable color output of logger in Clamp commands
:watch_plain: false
#
# # Forece relaod of Apipie cache with every Hammer invocation
:reload_cache: false
#
# # Directory where the logs are stored. The default is /var/log/hammer/ and the log file is named hammer.log
:log_dir: '~/.hammer/log'
#
# # Logging level. One of debug, info, warning, error, fatal
:log_level: 'debug'

 
:modules:
    - hammer_cli_foreman

:foreman:
    :host: 'https://foreman.example.com/'
    :username: admin
    :password: GRjCr9gF2TJQTnWg

