#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
ambari_repo_url: "{{ default_repo_site }}/ambari/ambari-{{ ambari_version }}/centos7"
ambari_server_mem: 2048
use_local_repository: no
hdp_repo_url: "{{ default_repo_site }}/HDP/HDP-{{ hdp_stack_version }}/centos7"
local_hdp_repository_url: "{{ hdp_repo_url }}"
hdp_utils_repo_url: "{{ default_repo_site }}/HDP/HDP-UTILS-{{ hdp_utils_version }}"
local_hdp_utils_repository_url: "{{ hdp_utils_repo_url }}"
hdp_os_type: "{{ hdp_os_type }}"
mysql_repo_url: "{{ default_repo_site}}/mysql"


