#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
- include_vars: "{{ cluster_type }}.yml"

- name: install python-requests
  yum:
    name: python-requests
    state: installed
  
- name: remove cluster with ambari; http://{{ groups.ambari_master[0] }}:{{ ambari_port }}
  ambari_cluster_state:
    host: "{{ groups.ambari_master[0] }}"
    port: "{{ ambari_port }}"
    username: "{{ ambari_user }}"
    password: "{{ ambari_password }}"
    cluster_name: "{{ cluster_name }}"
    cluster_state: absent
    wait_for_complete: True

- name: deploy cluster with ambari; http://{{ groups.ambari_master[0] }}:{{ ambari_port }}
  ambari_cluster_state:
    host: "{{ groups.ambari_master[0] }}"
    port: "{{ ambari_port }}"
    username: "{{ ambari_user }}"
    password: "{{ ambari_password }}"
    cluster_name: "{{ cluster_name }}"
    cluster_state: present
    blueprint_name: "{{ blueprint_name }}"
    configurations: "{{ configurations }}"
    wait_for_complete: True
    blueprint_var: "{{ blueprint }}"
    use_local_repository: "{{ use_local_repository }}"
