#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
- name: copy all test files to edge node
  become: True
  become_user: hdfs
  copy:
    src: ./tasks/tests/
    dest: /home/hdfs/
    mode: 0777

- name: run test for hdfs
  become: True
  become_user: root
  script: ./tests/hdfs/hdfs_test.sh
  register: hdfs_test
  failed_when: "'HDFS test is Failed' in hdfs_test.stdout"
 
- debug: msg="{{ hdfs_test.stdout }}"
- debug: msg="{{ hdfs_test.stderr }}"


- name: run test for yarn
  become: True
  become_user: hdfs
  script: ./tests/yarn/yarn_test.sh
  register: yarn_test
  failed_when: "'Yarn test is Failed' in yarn_test.stdout"

- debug: msg="{{ yarn_test.stdout }}"
- debug: msg="{{ yarn_test.stderr }}"


- name: run test for oozie
  become: True
  become_user: hdfs
  script:  ./tests/oozie/oozie_test.sh {{ oozie_url }} {{ oozie_name_node }} {{ oozie_job_tracker }}
  register: oozie_test
  failed_when: "'Failed' in oozie_test.stdout"

- debug: msg="{{ oozie_test.stdout }}"
- debug: msg="{{ oozie_test.stderr }}"


- name: run test for spark
  become: True
  become_user: hdfs
  script: ./tests/spark/spark_test.sh {{hdp_test_namenode_host}}
  register: spark_test
  failed_when: "'Failed' in spark_test.stdout"

- debug: msg="{{ spark_test.stdout }}"
- debug: msg="{{ spark_test.stderr }}"


- name: run test for hive
  become: True
  become_user: hdfs
  script: ./tests/hive/hive_test.sh
  register: hive_test
  failed_when: "'Failed' in hive_test.stdout"

- debug: msg="{{ hive_test.stdout }}"
- debug: msg="{{ hive_test.stderr }}"

- name: run test for pig
  become: True
  become_user: hdfs
  script: ./tests/pig/pig_test.sh
  register: pig_test
  failed_when: "'Failed' in pig_test.stdout"

- debug: msg="{{ pig_test.stdout }}"
- debug: msg="{{ pig_test.stderr }}"
