#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
- name: copy epel repo template
  template:
    src: "epel.repo"
    dest: "/etc/yum.repos.d/epel.repo"
    force: yes
- name: install epel release
  yum:
    name: epel-release
    state: installed
  register: result

- name: get the version of epel-release
  shell: yum list installed epel-release | grep epel-release | awk '{print $2}' | cut -d'-' -f1 | cut -d':' -f2
  register: version
  changed_when: False
  args:
    warn: no

- name: generate epel release report
  shell: "{{ playbook_dir }}/report.sh epel-release {{ version.stdout }} N/A N/A {{ ansible_fqdn }} success {{ inventoryname }}"
  delegate_to: localhost
  when: result|succeeded
  
