#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
# defaults file for activemq-ansible-role
activemq_user: activemq
activemq_group:  activemq
activemq_install_dir: /opt
activemq_run_dir: "/opt/{{ activemq_user }}"
activemq_home_dir:  /var/lib/activemq
activemq_log_dir: /var/log/activemq

# default installation mode
activemq_skip_checksum: true
activemq_repo_url: "{{ default_repo_site }}/activemq"
activemq_url_prefix: "{{ activemq_repo_url }}"

activemq_url: "{{ activemq_url_prefix }}/apache-activemq-{{ activemq_version }}-bin.tar.gz"

activemq_env_vars:
  ACTIVEMQ_USER: "{{ activemq_user }}"
  ACTIVEMQ_BASE: "{{ activemq_run_dir }}"
