#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
- hosts: localhost,all
  become: true
  roles:
    - role: init
 
- hosts: all
  become: true
  roles:
    - role: mdr_common
  tags:
    - ambari-prereqs
    - hdp-install

- hosts: postgres
  become: true
  roles:
    - role: postgresql

- hosts: activemq
  become: true
  roles:
    - role:  activemq

- hosts: ambari-server
  become: true
  roles:
    - role: ambari_server
  tags:
    - ambari-server
    - hdp-install


- hosts: ambari-agent
  become: true
  roles:
    - role: ambari_agent
  tags:
    - ambari-agent
    - hdp-install

- hosts: ambari-server
  become: true
  roles:
    - role: ambari_config
  tags:
    - hdp-deploy

- hosts: hdp_test
  become: true
  roles:
    - role:  hdp_test



- hosts: es-master
  roles:
    - { role: elasticsearch,es_heap_size: "1g",
    es_config: {
        network.host: 0.0.0.0,
        cluster.name: "es-cluster",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: false,
        node.master: true,
        bootstrap.memory_lock: false,
        }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: ansible

- hosts: es-node
  roles:
    - { role: elasticsearch,  es_data_dirs: "/opt/elasticsearch",
    es_config: {
        network.host: 0.0.0.0,
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        node.master: false,
        bootstrap.memory_lock: false,
        cluster.name: "es-cluster"
        }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: ansible
    es_api_port: 9200

- hosts: kibana
  become: true
  roles:
    - role: kibana

