#
## Software Copyright BAE Systems plc 2017. All Rights Reserved.
## BAE SYSTEMS, DETICA are trademarks of BAE Systems
## plc and may be registered in certain jurisdictions.
##
#---
## Create Config Files
  
- name: Update cluster hosts via ambari
  shell: 'cd {{ role_path }}  && python updatehdpcluster.py update_hdp_cluster.yml {{ambari_user}} {{ ambari_password}}'
  register: curllogs

- debug:
    msg: "{{ curllogs.stderr}}"
- debug:
    msg: "{{ curllogs.stdout }}"

