#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
- name: install ambari agent
  yum:
    name: ambari-agent
    state: installed
  register: result
  until: result.rc == 0
  retries: 5
  delay: 10

- name: create ambari agent hostname script
  template:
    src: "../roles/ambari_slave/files/hostname.sh"
    dest: "/var/lib/ambari-agent/hostname.sh"
    mode: 0744
    owner: "{{ ambari_installation_user }}"
    group: "{{ ambari_installation_user }}"

- name: configure ambari server hostname in ambari agent configuration
  lineinfile:
    dest: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter }}"
    backup: yes
  with_items:
    - { regexp: "^.*hostname=.*$", line: "hostname={{ groups.ambari_master[0] }}", insertafter: '\[server\]' }
    - { regexp: "^hostname_script=.*$", line: "hostname_script=/var/lib/ambari-agent/hostname.sh", insertafter: '\[agent\]'}

- name: start ambari agent
  service:
    name: ambari-agent
    state: restarted
    enabled: yes
  async: 20
  poll: 0

- name : check if ambari agent is up 
  wait_for : host={{ ansible_fqdn }} port=8670 delay=20

- name : wait for agent to register
  command : sleep 10
