---
- name: add mongodb community repo file
  template: src=repo.j2 dest=/etc/yum.repos.d/mongo-community.repo
  tags: mongodb

- name: install mongodb-org
  yum: name=mongodb-org state=present
  tags: mongodb
  register: result

- name: get the version of mongodb
  shell: yum list installed mongodb-org | grep mongodb-org | awk '{print $2}' | cut -d'-' -f1 | cut -d':' -f2
  register: version
  changed_when: False
  args:
    warn: no

- name: locating mongodb
  shell: whereis mongo | tr " " %
  register: path
  
- name: generate mongodb report
  shell: "{{ playbook_dir }}/report.sh mongodb {{ version.stdout }} N/A {{ path.stdout }} {{ ansible_fqdn }} success"
  delegate_to: localhost
  when: result|succeeded

- name: configure mongodb
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  tags: mongodb

- name: run mongodb
  service: name=mongod state=started enabled=yes
  tags: mongodb

- name: run mongo health check
  shell: echo 'db.stats().ok' | mongo {{ item }}:{{ mongod_port }}/test --quiet
  register: shell
  with_items:  
      - "{{groups['mongodb']}}" 
  failed_when: "'Failed' in shell.stdout"
- debug: msg="{{shell}}"

  
