#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
  - name: Copy postgres repo template
    template:
     src: "postgres.repo"
     dest: "/etc/yum.repos.d/postgres.repo"

  - shell: echo "{{ postgresql_version }}" | tr -d .
    register: postgresql_short_version
  
  - set_fact:
     network: "{{ ansible_default_ipv4.network }}"
  
  - set_fact:
     netmask: "{{ ansible_default_ipv4.netmask }}"
  
  - set_fact:
     network_mask: "{{ network }}/{{ netmask }}"
  
  - set_fact:
     prefix: "{{ network_mask | ipaddr('prefix') }}"
  
  - set_fact:
     postgres_subnet_access: "{{ network }}/{{ prefix }}"

  - set_fact:  
      postgresql_short_version: "{{ postgresql_short_version.stdout }}" 

  - name: Install New Postgresql Dependencies
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - postgresql{{ postgresql_short_version }}
      - postgresql{{ postgresql_short_version }}-contrib
      - pg_repack{{ postgresql_short_version }}
      - postgresql{{ postgresql_short_version }}-server
      - postgresql-jdbc
    register: result

  - name: get the version of postgresql
    shell: yum list installed postgresql{{ postgresql_short_version }} | grep postgresql{{ postgresql_short_version }} | awk '{print $2}' | cut -d'-' -f1 | cut -d':' -f2
    register: version
    changed_when: False
    args:
      warn: no
  
  - name: locating postgresql
    shell: whereis psql | tr " " %
    register: path
 
  - name: generate postgresql report
    shell: "{{ playbook_dir }}/report.sh postgresql {{ version.stdout }} N/A {{ path.stdout }} {{ ansible_fqdn }} success"
    delegate_to: localhost
    when: result|succeeded

  - name: Change Postgresql-JDBC Permission
    file:
      path: "/usr/share/java/postgresql-jdbc.jar"
      mode: "0644"

  - name: Remove Postgres Data Folder
    file:
      path: "/var/lib/pgsql/{{postgresql_version}}/data"
      state: absent

  - name: Initiate the Database
    shell: "/usr/pgsql-{{ postgresql_version }}/bin/postgresql{{ postgresql_short_version }}-setup initdb"

  - name: Copy custom Postgresql.conf to "{{ postgres_data_location }}"
    template:
      src: templates/postgresql.conf
      dest: "{{ postgres_data_location }}"
      mode: "0751"

  - name: Copy Custom pg_hba.conf to "{{ postgres_data_location }}"
    template:
      src: templates/pg_hba.conf
      dest: "{{ postgres_data_location }}"
      mode: "0751"

  - name: Link 'pgsql' to the new Postgres version
    file:
      path: /usr/bin/psql
      src: "/usr/pgsql-{{ postgresql_version }}/bin/psql"
      state: link
      force: yes

  - name: Start the Postgres service
    service:
      name: "{{ postgresql_service_name }}"
      state: started

  - name: Enable the Postgres service
    service:
      name: "{{ postgresql_service_name }}"
      enabled: yes

  - name: change mode for postgres_test.sh
    become: True
    become_user: root
    copy:
      src: ./tests/postgres_test.sh
      dest: /root/
      mode: 0777

  - name: run test for postgres
    become: True
    become_user: root
    script: ./tests/postgres_test.sh
    register: postgres_test
    failed_when: "'Failed' in postgres_test.stdout"
  
  - debug: msg="{{ postgres_test.stdout }}"
  - debug: msg="{{ postgres_test.stderr }}"
