#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
- name: copy init files to nodes
  become: True
  become_user: root
  copy:
    src: ./tasks/
    dest: /home/
    mode: 0777

- name: check and remove host_list entry in /etc/hosts of nodes since dns is enabled
  become: True
  become_user: root
  command: sed -i '/mdr_hosts_begins/,/mdr_hosts_ends/d' /etc/hosts
  when: default_dns_enabled
 
- name: host_list entry into /etc/hosts of nodes since dns is disabled
  become: True
  become_user: root
  script: /home/all_config/localhost_config.sh
  when: not default_dns_enabled

- name: remove the existing repos in nodes
  become: True
  become_user: root
  script: /home/all_config/repos_config.sh 
  when: inventory_hostname != "localhost"