---
- name: configure passenger nginx yum repository
  template:
    src=passenger_nginx.repo.j2
    dest=/etc/yum.repos.d/passenger_nginx.repo
  when: ansible_os_family == "RedHat"

- name: configure passenger nginx rpm key
  rpm_key:
    key="{{ passenger_nginx_yum_key }}"
    state=present
  when: ansible_os_family == "RedHat" and passenger_nginx_yum_gpg


