---
- name: Ensure libselinux-python on CentOS 6.x
  become: yes
  yum: name=libselinux-python state=present update_cache=yes
  when: ( ansible_distribution == "CentOS" ) and ( ansible_distribution_major_version == "6" )

- name: RedHat - add Elasticsearch repo
  become: yes
  template: src=elasticsearch.repo dest=/etc/yum.repos.d/elasticsearch-{{ es_major_version }}.repo
  when: es_use_repository

- name: RedHat - include versionlock
  include: elasticsearch-RedHat-version-lock.yml
  when: es_version_lock

- name: RedHat - Install Elasticsearch
  become: yes
  yum: name=elasticsearch{% if es_version is defined and es_version != ""  %}-{{ es_version }}{% endif %} state=present update_cache=yes
  when: es_use_repository
  register: redhat_elasticsearch_install_from_repo
  notify: restart elasticsearch
  until: '"failed" not in redhat_elasticsearch_install_from_repo'
  retries: 5
  delay: 10

- name: get the version of elasticsearch
  shell: yum list installed elasticsearch | grep elasticsearch | awk '{print $2}' | cut -d'-' -f1 | cut -d':' -f2
  register: version
  changed_when: False
  args:
    warn: no

- name: locating elasticsearch
  shell: whereis elasticsearch | tr " " %
  register: path
  
- name: generate elasticsearch report
  shell: "{{ playbook_dir }}/report.sh elasticsearch {{ version.stdout }} N/A {{ path.stdout }} {{ ansible_fqdn }} success"
  delegate_to: localhost
  when: redhat_elasticsearch_install_from_repo|succeeded

- name: RedHat - Install Elasticsearch from url
  become: yes
  yum: name={% if es_custom_package_url is defined %}{{ es_custom_package_url }}{% else %}{{ es_package_url }}-{{ es_version }}.noarch.rpm{% endif %} state=present
  when: not es_use_repository
  register: elasticsearch_install_from_package
  notify: restart elasticsearch
