#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---

master_1_components : [JOURNALNODE,NAMENODE,METRICS_MONITOR,HISTORYSERVER]
master_2_components: [JOURNALNODE,APP_TIMELINE_SERVER,RESOURCEMANAGER,SPARK_JOBHISTORYSERVER,METRICS_MONITOR]
master_3_components: [SECONDARY_NAMENODE,HCAT,HIVE_METASTORE,HIVE_SERVER,HIVE_CLIENT,WEBHCAT_SERVER,MYSQL_SERVER,METRICS_MONITOR]
master_4_components: [OOZIE_SERVER,METRICS_MONITOR]
zk_1_components: [METRICS_MONITOR,ZOOKEEPER_SERVER]
worker_1_components: [NODEMANAGER,DATANODE,METRICS_MONITOR]
edge_1_components: [METRICS_MONITOR,METRICS_COLLECTOR]
edge_3_components: [ZOOKEEPER_CLIENT,TEZ_CLIENT,OOZIE_CLIENT,METRICS_MONITOR,MAPREDUCE2_CLIENT,YARN_CLIENT,HDFS_CLIENT,SPARK_CLIENT,HIVE_CLIENT,PIG]

cluster_name: "mdr"
blueprint_name: "mdr_ha_blueprint"

configurations: []
blueprint:
  stack_name: HDP
  stack_version: "{{ hdp_stack }}"
  groups:
    - name : master_1
      cardinality: 1
      configuration: []  # configuration not yet implemented
      components: "{{ master_1_components }}"
      hosts: "{{ master_1_host }}"
    - name : master_2
      cardinality: 1
      configuration: []  # configuration not yet implemented
      components: "{{ master_2_components }}"
      hosts: "{{ master_2_host }}"
    - name : master_3
      cardinality: 1
      configuration: []  # configuration not yet implemented
      components: "{{ master_3_components }}"
      hosts: "{{ master_3_host }}"
    - name : master_4
      cardinality: 1
      configuration: []  # configuration not yet implemented
      components: "{{ master_4_components }}"
      hosts: "{{ master_4_host }}"
    - name : edge_1
      cardinality: 1
      configuration: []  # configuration not yet implemented
      components: "{{ edge_1_components }}"
      hosts: "{{ edge_1_host }}"
    - name : edge_3
      cardinality: 2
      configuration: []  # configuration not yet implemented
      components: "{{ edge_3_components }}"
      hosts: "{{ edge_3_host }}"
    - name : zk_1
      cardinality: 3
      configuration: []  # configuration not yet implemented
      components: "{{ zk_1_components }}"
      hosts: "{{ zk_1_host }}"
    - name : worker_1
      cardinality: 6
      configuration: []  # configuration not yet implemented
      components: "{{ worker_1_components }}"
      hosts: "{{ worker_1_host }}"
 
