#!/bin/bash


setBaseRepo(){

    base_name="CentOS-\$releasever - Base"
    base_url="$repo_url/repos/centos/7/os/\$basearch"
    base_gpgkey="$repo_url/repos/pki/\$basearch/RPM-GPG-KEY-CentOS-7"
    update_name="CentOS-\$releasever - Updates"
    update_url="$repo_url/repos/centos/7/updates/\$basearch"
    update_gpgkey="$repo_url/repos/pki/\$basearch/RPM-GPG-KEY-CentOS-7"


tee /etc/yum.repos.d/CentOS-Base.repo <<EOF
[base]
name=$base_name
gpgcheck=1
gpgkey=$base_gpgkey
baseurl=$base_url

[update]
name=$update_name
gpgcheck=1
gpgkey=$update_gpgkey
baseurl=$update_url
EOF
}

setEpelRepo(){

    epel_name="Extra Packages for Enterprise Linux 7 - \$basearch"
    epel_url="$repo_url/repos/epel/7/\$basearch"
    epel_gpgkey="$repo_url/repos/pki/\$basearch/RPM-GPG-KEY-EPEL-7"

tee /etc/yum.repos.d/epel.repo <<EOF
[epel]
name=$epel_name
enabled=1
gpgcheck=1
gpgkey=$epel_gpgkey
baseurl=$epel_url
EOF
}

