---
# This playbook deploys foreman together with passenger_nginx and mysql
# including foreman-proxy, tftp and dhcp
- hosts: 127.0.0.1
  gather_facts: no
  vars_files:
    - fmconfig/payload.yml.j2
    - vars/fm_database.yml
  roles:
    - { role: common }
    - { role: mysql }
    - { role: isc_dhcp_server }
    - { role: tftp }
    - { role: foreman }
    - { role: foreman_proxy }
    - { role: passenger_nginx }
    - { role: fmclient }
  

