#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
- hosts: localhost,all
  become: true
  tasks:
   - block:
      - include_role:
          name: init
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute init role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute init role in {{ ansible_fqdn }}"
        register: init_info
        failed_when: "'Failed' in init_info.stdout"
      
  
    
- hosts: all
  become: true
  tasks:
   - block:
     - include_role:
          name: mdr_common
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute mdr_common role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute mdr_common role in {{ ansible_fqdn }}"
        register: mdr_common_info
        failed_when: "'Failed' in mdr_common_info.stdout"
  tags:
    - ambari-prereqs
    - hdp-install


- hosts: httpd
  become: true
  tasks:
   - block:
      - include_role:
          name: httpd
     rescue:
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute httpd role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute httpd role in {{ ansible_fqdn }}"
        register: httpd_info
        failed_when: "'Failed' in httpd_info.stdout"
  

- hosts: activemq
  become: true
  tasks:
   - block:
      - include_role:
          name: activemq
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute activemq role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute activemq role in {{ ansible_fqdn }}"
        register: activemq_info
        failed_when: "'Failed' in activemq_info.stdout"
  

- hosts: docker
  become: true
  tasks:
   - block:
      - include_role:
          name: docker
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute docker role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute docker role in {{ ansible_fqdn }}"
        register: docker_info
        failed_when: "'Failed' in docker_info.stdout"
  

- hosts: apache
  become: true
  tasks:
   - block:
      - include_role:
          name: apache
      - include_role:
          name: python-pip
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute apache or python-pip role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute apache or python-pip role in {{ ansible_fqdn }}"
        register: apache_info
        failed_when: "'Failed' in apache_info.stdout"
  

- hosts: postgres
  become: true
  tasks:
   - block:
      - include_role:
          name: postgresql
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute postgresql role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute postgresql role in {{ ansible_fqdn }}"
        register: postgresql_info
        failed_when: "'Failed' in postgresql_info.stdout"
    
- hosts: es_master
  tasks:
   - block:
      - include_role:
          name: elasticsearch
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute elasticsearch role for master in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute elasticsearch role for master in {{ ansible_fqdn }}"
        register: elasticsearch_info
        failed_when: "'Failed' in elasticsearch_info.stdout"
  vars:
    es_type: master
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: ansible

- hosts: es_node
  tasks:
   - block:
      - include_role:
          name: elasticsearch
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute elasticsearch role for node in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute elasticsearch role for node in {{ ansible_fqdn }}"
        register: elasticsearch_info
        failed_when: "'Failed' in elasticsearch_info.stdout"
  vars:
    es_type: data
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: ansible

- hosts: kibana
  become: true
  tasks:
   - block:
      - include_role:
          name: kibana
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute kibana role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute kibana role in {{ ansible_fqdn }}"
        register: kibana_info
        failed_when: "'Failed' in kibana_info.stdout"
  

- hosts: mongodb
  become: true
  tasks:
   - block:
      - include_role:
          name: mongodb
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute mongodb role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute mongodb role in {{ ansible_fqdn }}"
        register: mongodb_info
        failed_when: "'Failed' in mongodb_info.stdout"

- hosts: ambari
  become: true
  tasks:
   - block:
      - include_role:
          name: ambari_server
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute ambari_server role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute ambari_server role in {{ ansible_fqdn }}"
        register: ambari_server_info
        failed_when: "'Failed' in ambari_server_info.stdout"
  tags:
    - ambari-server
    - hdp-install

- hosts: hdp
  become: true
  tasks:
   - block:
      - include_role:
          name: ambari_agent
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute ambari_agent role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute ambari_agent role in {{ ansible_fqdn }}"
        register: ambari_agent_info
        failed_when: "'Failed' in ambari_agent_info.stdout"
  tags:
    - ambari-agent
    - hdp-install



- hosts: ambari
  become: true
  tasks:
   - block:
      - include_role:
          name: ambari_config
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute ambari_config role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute ambari_config role in {{ ansible_fqdn }}"
        register: ambari_config_info
        failed_when: "'Failed' in ambari_config_info.stdout"
  tags:
    - hdp-deploy

- hosts: hdp_test
  become: true
  tasks:
   - block:
      - include_role:
          name: hdp_test
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute hdp_test role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute hdp_test role in {{ ansible_fqdn }}"
        register: hdp_test_info
        failed_when: "'Failed' in hdp_test_info.stdout"
  

- hosts: localhost,all
  become: true
  tasks:
   - block:
      - include_role:
          name: cleanup
     rescue:
      - include_role:
          name: httpd
      - include_role:
          name: overall_report
      - shell: sed -i '0,/{/s//{"error":"Failed to execute cleanup role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute cleanup role in {{ ansible_fqdn }}"
        register: cleanup_info
        failed_when: "'Failed' in cleanup_info.stdout"
      
- hosts: localhost,all
  tasks:
   - block:
      - yum:
          name: httpd-{{ httpd_version}}
          state: absent
        when: "'httpd' not in group_names"
     rescue:
       - shell: sed -i '0,/{/s//{"error":"Failed to remove httpd in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
       - shell: echo {{ inventoryname }} | tr " " %
         register: format_inventoryname
       - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
         delegate_to: localhost
       - shell: echo "Failed to remove httpd in {{ ansible_fqdn }}"
         register: remove_httpd_info
         failed_when: "'Failed' in remove_httpd_info.stdout"
   

- hosts: httpd
  become: true
  tasks:
   - block:
      - include_role:
          name: overall_report
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
     rescue:
      - shell: sed -i '0,/{/s//{"error":"Failed to execute overall_report role in {{ ansible_fqdn }}",/' /var/www/html/{{ inventoryname }}_overall_report.json
      - shell: echo {{ inventoryname }} | tr " " %
        register: format_inventoryname
      - shell: "{{ playbook_dir }}/browse_report.sh {{ ansible_fqdn }} {{ format_inventoryname.stdout }}"
        delegate_to: localhost
      - shell: echo "Failed to execute overall_report role in {{ ansible_fqdn }}"
        register: overall_report_info
        failed_when: "'Failed' in overall_report_info.stdout"
      

