#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
- hosts: localhost
  become: true
  roles:
    - init

- hosts: all
  become: true
  roles:
    - init
    - mdr_common
  tags:
    - ambari-prereqs
    - hdp-install

- hosts: postgres_hosts
  become: true
  roles:
    - role: postgresql

- hosts: activemq_hosts
  become: true
  roles:
    - role:  activemq

- hosts: docker-registry_hosts
  become: true
  roles:
    - role: docker-registry

- hosts: apache-server_hosts
  become: true
  roles:
    - apache-server
    - python-pip
    
- hosts: ambari_hosts
  become: true
  roles:
    - role: ambari_server
  tags:
    - ambari-server
    - hdp-install

- hosts: hdp_hosts
  become: true
  roles:
    - role: ambari_agent
  tags:
    - ambari-agent
    - hdp-install

- hosts: ambari_hosts
  become: true
  roles:
    - role: ambari_config
  tags:
    - hdp-deploy

- hosts: hdp_test_hosts
  become: true
  roles:
    - role:  hdp_test



- hosts: es_master_hosts
  roles:
    - { role: elasticsearch,es_heap_size: "1g",
    es_config: {
        network.host: 0.0.0.0,
        cluster.name: "es-cluster",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: false,
        node.master: true,
        bootstrap.memory_lock: false,
        }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: ansible

- hosts: es_node_hosts
  roles:
    - { role: elasticsearch,  es_data_dirs: "/opt/elasticsearch",
    es_config: {
        network.host: 0.0.0.0,
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        node.master: false,
        bootstrap.memory_lock: false,
        cluster.name: "es-cluster"
        }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: ansible
    es_api_port: 9200

- hosts: kibana_hosts
  become: true
  roles:
    - role: kibana

- hosts: mongodb_hosts
  become: true
  roles:
    - role:  mongodb

- hosts: all
  become: true
  roles:
    - role: cleanup

- hosts: apache-server_hosts
  become: true
  roles:
    - overall_report