#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
- hosts: localhost
  become: true
  roles:
    - init

- hosts: all
  become: true
  roles:
    - init
    - mdr_common
  tags:
    - ambari-prereqs
    - hdp-install


- hosts: httpd
  become: true
  roles:
    - httpd

- hosts: activemq
  become: true
  roles:
    - role:  activemq

- hosts: docker
  become: true
  roles:
    - role: docker

- hosts: apache
  become: true
  roles:
    - apache
    - python-pip

- hosts: postgres
  become: true
  roles:
    - role: postgresql
    
- hosts: es_master
  roles:
    - role: elasticsearch
  vars:
    es_type: master
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: ansible

- hosts: es_node
  roles:
    - role: elasticsearch
  vars:
    es_type: data
    es_scripts: false
    es_templates: false
    es_version_lock: false
    ansible_user: ansible

- hosts: kibana
  become: true
  roles:
    - role: kibana

- hosts: mongodb
  become: true
  roles:
    - role:  mongodb

- hosts: ambari
  become: true
  roles:
    - role: ambari_server
  tags:
    - ambari-server
    - hdp-install

- hosts: hdp
  become: true
  roles:
    - role: ambari_agent
  tags:
    - ambari-agent
    - hdp-install



- hosts: ambari
  become: true
  roles:
    - role: ambari_config
  tags:
    - hdp-deploy

- hosts: hdp_test
  become: true
  roles:
    - role:  hdp_test

- hosts: localhost,all
  become: true
  roles:
    - role: cleanup



- hosts: httpd
  become: true
  roles:
    - overall_report
