default:
  java_vendor: oracle
  dns_enabled: no

es_master:
  host: agent3-ambariagent.example.com
  version: 5.5.0
  es_heap_size: "1g"

es_node:
  add:
    hosts:
       - name: agent8-ambariagent.example.com
         ip: 10.11.12.10
  remove:
    hosts:
       - name: agent14-ambariagent.example.com
  es_config:
    network.host: 0.0.0.0
    cluster.name: "es-cluster"
    http.port: 9200
    transport.tcp.port: 9300
    node.data: true
    node.master: false
    bootstrap.memory_lock: false 
  es_api_port: 9200
