#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---
zookeeper_data_dir: /hadoop/zookeeper
namenode_checkpoint_dir: /hadoop/hdfs/namesecondary
namenode_name_dir: /hadoop/hdfs/namenode
datanode_data_dir: /hadoop/hdfs/data
journalnode_edits_dir: /hadoop/hdfs/journalnode
jhs_recovery_store_ldb_path: /hadoop/mapreduce/jhs
nodemanager_local_dirs: /hadoop/yarn/local
timeline_ldb_store_path: /hadoop/yarn/timeline
timeline_ldb_state_path: /hadoop/yarn/timeline
nodemanager_log_dirs: /hadoop/yarn/log
cluster_type: single_node_vm
nodemanager_mem_mb : 4096
mapred_map_java_opts : -Xmx1024m
mapred_reduce_java_opts : -Xmx1024m
mapred_map_mem_mb : 1229
mapred_reduce_mem_mb : 1229
topology_classpath: '/etc/hbase/conf:/etc/hadoop/conf'
elasticsearch_network_interface: _site_
