---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Docker.
  package: name={{ docker_package }} state={{ docker_package_state }}

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes

- name: Install Docker Regisry.
  package: name={{ docker_registry }} state={{ docker_package_state }}

- name: "Create symbolic link /usr/lib/systemd/system/docker-registry to /usr/lib/systemd/system/docker-distribution.service"
  file:
    src: "/usr/lib/systemd/system/docker-distribution.service"
    dest: "/usr/lib/systemd/system/docker-registry.service"
    state: link
    owner: "root"
    group: "root"

- name: Ensure Docker registry is started and enabled at boot
  service:
    name: docker-registry
    state: started
    enabled: yes

- name: run test for docker-registry
  become: True
  become_user: root
  script: ./tests/registry_test.sh
  register: registry_test

- debug: msg="{{ registry_test.stdout }}"
- debug: msg="{{ registry_test.stderr }}"
