#
# Software Copyright BAE Systems plc 2017. All Rights Reserved.
# BAE SYSTEMS, DETICA are trademarks of BAE Systems
# plc and may be registered in certain jurisdictions.
#
---

pgsql_repo_url: "{{ default_repo_site}}/postgresql"
postgres_data_location: "/var/lib/pgsql/{{ postgresql_version }}/data"
postgresql_version: "{{ postgres_version }}"
postgresql_service_name: "postgresql-{{ postgresql_version }}"
postgresql_port: 5432
