---
- name: configure foreman yum repository
  template:
    src=foreman.repo.j2
    dest=/etc/yum.repos.d/foreman.repo
  when: ansible_os_family == "RedHat"

- name: configure foreman plugins yum repository
  template:
    src=foreman_plugins.repo.j2
    dest=/etc/yum.repos.d/foreman_plugins.repo
  when: ansible_os_family == "RedHat" and foreman_proxy_plugins_repo 

- name: configure additional repositories
  package:
    name="{{ item }}"
    state=present
  with_items: "{{ foreman_proxy_extra_repos_pkg }}"

- name: configure foreman rpm key
  rpm_key:
    key="{{ foreman_proxy_yum_main_key }}"
    state=present
  when: ansible_os_family == "RedHat" and foreman_proxy_yum_main_gpg

- name: configure foreman plugins rpm key
  rpm_key:
    key="{{ foreman_proxy_yum_plugins_key }}"
    state=present
  when: ansible_os_family == "RedHat" and foreman_proxy_yum_plugins_gpg and foreman_proxy_plugins_repo


