- name: change_ambari-agent.ini for server
  lineinfile:
    dest: "/etc/ambari-agent/conf/ambari-agent.ini"
    line: "hostname={{ ambari_agent_servername }}"
    insertafter: '^\[server\]'
    regexp: '^hostname\='
    state: present
  
- name: change_ambari-agent.ini for agent
  lineinfile:
    dest: "/etc/ambari-agent/conf/ambari-agent.ini"
    line: "hostname_script=/var/lib/ambari-agent/hostname.sh"
    insertafter: '^\[agent\]'
    state: present
  notify:
    - restart_ambari_agent
    - check_ambari_agent_restarted
   
- name: copy_hostname.sh
  template: src=hostname.sh dest=/var/lib/ambari-agent/hostname.sh

- name: chmod_hostname.sh
  file: path=/var/lib/ambari-agent/hostname.sh mode=655


